#: import sm kivy.uix.screenmanager

ScreenManagement:
    transition: sm.NoTransition()
    UserScreen:
    TestScreen:
    ProgressBarScreen:
    CreateNewUserScreen

<TestScreen>:
    name: 'tests'
    Button:
        id: btn
        text: 'Select Test'
        on_release: dropdown.open(self)
        size_hint: .4, .05
        pos_hint: {'x':.3, 'y':.5}

    Widget

    DropDown:
        id: dropdown
        on_select: btn.text = '{}'.format(args[1])

        Button:
            text: 'Test A'
            size_hint_y: None
            height: '30dp'
            on_press: dropdown.select('Test A')

        Button:
            text: 'Test B'
            size_hint_y: None
            height: '30dp'
            on_press: dropdown.select('Test B')

        Button:
            text: 'Test C'
            size_hint_y: None
            height: '30dp'
            on_press: dropdown.select('Test C')

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'

        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, .1
            Button:
                text: 'Exit'
                on_press: app.stop()
            Button:
                text: 'Back to Login'
                on_press: app.root.current = 'demo'
            Button:
                text: 'Start Test'
                on_press: root.recordTest(btn.text)
                on_release: app.root.current = 'progressbar'

<ProgressBarScreen>:
    name: 'progressbar'
    Button:
        text: 'Back to Login'
        size_hint: .3, .05
        on_press: app.root.current = 'demo'

<CreateNewUserScreen>:
    name: 'newuser'
    TextInput:
        id: newusertext
        text: ''
        size_hint: .4, .05
        pos_hint: {'x':.3, 'y':.5}
    Button:
        id: submit
        text: 'Submit'
        size_hint: .3, .05
        pos_hint: {'x':.35, 'y':.44}
        on_press: root.createNewUser(newusertext.text)
        on_release: app.root.current = 'demo'

<UserScreen>
    name: 'demo'
    on_pre_enter: root.refresh()
    Button:
        text: "Create New User"
        on_press: app.root.current = 'newuser'
        pos_hint: {'x':.5, 'y':.45}
        size_hint: .2, .04

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'

        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, .1
            Button:
                text: 'Exit'
                on_press: app.stop()
            Button:
                text: 'Choose Test'
                on_press: app.root.current = 'tests'
                on_release: root.recordUser()