#: import sm kivy.uix.screenmanager

ScreenManagement:
    transition: sm.NoTransition()
    LoginScreen:
    TestScreen:
    UserScreen:
    ProgressBarScreen:
    CreateNewUserScreen

<LoginScreen>:
    name: 'welcome'
    Label:
        markup: True
        text: '[size=24]Welcome to [color=dd88ff]THE APP[/color][/size]'

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'

        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, .1
            Button:
                text: 'Exit'
                on_press: app.Exit()
            Button:
                text: 'Login'
                on_press: app.root.current = 'login'

<TestScreen>:
    name: 'tests'
    Button:
        id: btn
        text: 'Select Test'
        on_release: dropdown.open(self)
        size_hint: .4, .05
        pos_hint: {'x':.3, 'y':.5}

    Widget

    DropDown:
        id: dropdown
        on_select: btn.text = '{}'.format(args[1])

        Button:
            text: 'Test A'
            size_hint_y: None
            height: '40dp'
            on_press: dropdown.select('Test A')
            on_release: root.saveTest('Test A')

        Button:
            text: 'Test B'
            size_hint_y: None
            height: '40dp'
            on_press: dropdown.select('Test B')
            on_release: root.saveTest('Test B')

        Button:
            text: 'Test C'
            size_hint_y: None
            height: '40dp'
            on_press: dropdown.select('Test C')
            on_release: root.saveTest('Test C')

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'

        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, .1
            Button:
                text: 'Exit'
                on_press: app.Exit()
            Button:
                text: 'Back to Login'
                on_press: app.root.current = 'login'
            Button:
                text: 'Start Test'
                on_press: app.root.current = 'progressbar'

<UserScreen>:
    name: 'login'
    Button:
        id: btn2
        text: 'Select User'
        on_release: dropdown2.open(self)
        size_hint: .4, .05
        pos_hint: {'x':.3, 'y':.5}

    Widget

    DropDown:
        id: dropdown2
        on_select: btn2.text = '{}'.format(args[1])

        Button:
            text: 'User 1'
            size_hint_y: None
            height: '40dp'
            on_press: dropdown2.select('User 1')
            on_release: root.saveUser('User 1')

        Button:
            text: 'User 2'
            size_hint_y: None
            height: '40dp'
            on_press: dropdown2.select('User 2')
            on_release: root.saveUser('User 2')

        Button:
            text: 'User 3'
            size_hint_y: None
            height: '40dp'
            on_press: dropdown2.select('User 3')
            on_release: root.saveUser('User 3')

    Button:
        text: "Create New User"
        on_press: app.root.current = 'newuser'
        pos_hint: {'x':.5, 'y':.44}
        size_hint: .2, .04

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'

        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, .1
            Button:
                text: 'Exit'
                on_press: app.Exit()
            Button:
                text: 'Back to Welcome'
                on_press: app.root.current = 'welcome'
            Button:
                text: 'Choose Test'
                on_press: app.root.current = 'tests'


<ProgressBarScreen>:
    name: 'progressbar'

<CreateNewUserScreen>:
    name: 'newuser'
    TextInput:
        id: newusertext
        text: ''
        size_hint: .4, .05
        pos_hint: {'x':.3, 'y':.5}
    Button:
        id: submit
        text: 'Submit'
        size_hint: .3, .05
        pos_hint: {'x':.35, 'y':.44}
        on_press: root.createNewUser(newusertext.text)
        on_release: app.root.current = 'login'
